// Generated route table. access is 'public' or the roles allowed in.
export const routes = [
  { path: "/", view: "home", access: "public", title: "Home" },
  { path: "/sign-in", view: "signIn", access: "public", title: "Sign in" },
  { path: "/no-access", view: "noAccess", access: "public", title: "No access" },
  { path: "/status/outage", view: "outage", access: "public", title: "Service status" },
  { path: "/archive", view: "archive", access: "public", title: "Archive" },
  { path: "/legacy-export", view: "legacyExport", access: "public", title: "Legacy export" },
  { path: "/orders", view: "list", feature: "orders", access: "public", title: "Orders" },
  { path: "/orders/new", view: "new", feature: "orders", access: "public", title: "Add order" },
  { path: "/orders/:id", view: "detail", feature: "orders", access: "public", title: "Order detail" },
  { path: "/audits", view: "list", feature: "audits", access: "public", title: "Audits" },
  { path: "/audits/new", view: "new", feature: "audits", access: "public", title: "Add audit" },
  { path: "/audits/:id", view: "detail", feature: "audits", access: "public", title: "Audit detail" },
  { path: "/subscriptions", view: "list", feature: "subscriptions", access: "public", title: "Subscriptions" },
  { path: "/subscriptions/new", view: "new", feature: "subscriptions", access: "public", title: "Add subscription" },
  { path: "/subscriptions/:id", view: "detail", feature: "subscriptions", access: "public", title: "Subscription detail" },
  { path: "/invoices", view: "list", feature: "invoices", access: ["manager","admin"], title: "Invoices" },
  { path: "/invoices/new", view: "new", feature: "invoices", access: ["manager","admin"], title: "Add invoice" },
  { path: "/invoices/:id", view: "detail", feature: "invoices", access: ["manager","admin"], title: "Invoice detail" },
  { path: "/reports", view: "list", feature: "reports", access: "public", title: "Reports" },
  { path: "/reports/new", view: "new", feature: "reports", access: "public", title: "Add report" },
  { path: "/reports/:id", view: "detail", feature: "reports", access: "public", title: "Report detail" },
  { path: "/courses", view: "list", feature: "courses", access: ["member","manager","admin"], title: "Courses" },
  { path: "/courses/new", view: "new", feature: "courses", access: ["member","manager","admin"], title: "Add course" },
  { path: "/courses/:id", view: "detail", feature: "courses", access: ["member","manager","admin"], title: "Course detail" },
  { path: "/returns", view: "list", feature: "returns", access: "public", title: "Returns" },
  { path: "/returns/new", view: "new", feature: "returns", access: "public", title: "Add return" },
  { path: "/returns/:id", view: "detail", feature: "returns", access: "public", title: "Return detail" },
  { path: "/claims", view: "list", feature: "claims", access: ["admin"], title: "Claims" },
  { path: "/claims/new", view: "new", feature: "claims", access: ["admin"], title: "Add claim" },
  { path: "/claims/:id", view: "detail", feature: "claims", access: ["admin"], title: "Claim detail" },
  { path: "/contracts", view: "list", feature: "contracts", access: "public", title: "Contracts" },
  { path: "/contracts/new", view: "new", feature: "contracts", access: "public", title: "Add contract" },
  { path: "/contracts/:id", view: "detail", feature: "contracts", access: "public", title: "Contract detail" },
  { path: "/surveys", view: "list", feature: "surveys", access: "public", title: "Surveys" },
  { path: "/surveys/new", view: "new", feature: "surveys", access: "public", title: "Add survey" },
  { path: "/surveys/:id", view: "detail", feature: "surveys", access: "public", title: "Survey detail" },
  { path: "/venues", view: "list", feature: "venues", access: "public", title: "Venues" },
  { path: "/venues/new", view: "new", feature: "venues", access: "public", title: "Add venue" },
  { path: "/venues/:id", view: "detail", feature: "venues", access: "public", title: "Venue detail" },
  { path: "/tickets", view: "list", feature: "tickets", access: ["manager","admin"], title: "Tickets" },
  { path: "/tickets/new", view: "new", feature: "tickets", access: ["manager","admin"], title: "Add ticket" },
  { path: "/tickets/:id", view: "detail", feature: "tickets", access: ["manager","admin"], title: "Ticket detail" },
  { path: "/vendors", view: "list", feature: "vendors", access: "public", title: "Vendors" },
  { path: "/vendors/new", view: "new", feature: "vendors", access: "public", title: "Add vendor" },
  { path: "/vendors/:id", view: "detail", feature: "vendors", access: "public", title: "Vendor detail" },
  { path: "/budgets", view: "list", feature: "budgets", access: ["member","manager","admin"], title: "Budgets" },
  { path: "/budgets/new", view: "new", feature: "budgets", access: ["member","manager","admin"], title: "Add budget" },
  { path: "/budgets/:id", view: "detail", feature: "budgets", access: ["member","manager","admin"], title: "Budget detail" },
  { path: "/campaigns", view: "list", feature: "campaigns", access: "public", title: "Campaigns" },
  { path: "/campaigns/new", view: "new", feature: "campaigns", access: "public", title: "Add campaign" },
  { path: "/campaigns/:id", view: "detail", feature: "campaigns", access: "public", title: "Campaign detail" },
  { path: "/meetings", view: "list", feature: "meetings", access: ["admin"], title: "Meetings" },
  { path: "/meetings/new", view: "new", feature: "meetings", access: ["admin"], title: "Add meeting" },
  { path: "/meetings/:id", view: "detail", feature: "meetings", access: ["admin"], title: "Meeting detail" },
  { path: "/shipments", view: "list", feature: "shipments", access: "public", title: "Shipments" },
  { path: "/shipments/new", view: "new", feature: "shipments", access: "public", title: "Add shipment" },
  { path: "/shipments/:id", view: "detail", feature: "shipments", access: "public", title: "Shipment detail" },
  { path: "/vehicles", view: "list", feature: "vehicles", access: "public", title: "Vehicles" },
  { path: "/vehicles/new", view: "new", feature: "vehicles", access: "public", title: "Add vehicle" },
  { path: "/vehicles/:id", view: "detail", feature: "vehicles", access: "public", title: "Vehicle detail" },
  { path: "/projects", view: "list", feature: "projects", access: "public", title: "Projects" },
  { path: "/projects/new", view: "new", feature: "projects", access: "public", title: "Add project" },
  { path: "/projects/:id", view: "detail", feature: "projects", access: "public", title: "Project detail" },
  { path: "/warehouses", view: "list", feature: "warehouses", access: ["manager","admin"], title: "Warehouses" },
  { path: "/warehouses/new", view: "new", feature: "warehouses", access: ["manager","admin"], title: "Add warehouse" },
  { path: "/warehouses/:id", view: "detail", feature: "warehouses", access: ["manager","admin"], title: "Warehouse detail" },
  { path: "/inspections", view: "list", feature: "inspections", access: "public", title: "Inspections" },
  { path: "/inspections/new", view: "new", feature: "inspections", access: "public", title: "Add inspection" },
  { path: "/inspections/:id", view: "detail", feature: "inspections", access: "public", title: "Inspection detail" },
  { path: "/licenses", view: "list", feature: "licenses", access: ["member","manager","admin"], title: "Licenses" },
  { path: "/licenses/new", view: "new", feature: "licenses", access: ["member","manager","admin"], title: "Add license" },
  { path: "/licenses/:id", view: "detail", feature: "licenses", access: ["member","manager","admin"], title: "License detail" },
  { path: "/shifts", view: "list", feature: "shifts", access: "public", title: "Shifts" },
  { path: "/shifts/new", view: "new", feature: "shifts", access: "public", title: "Add shift" },
  { path: "/shifts/:id", view: "detail", feature: "shifts", access: "public", title: "Shift detail" },
  { path: "/suppliers", view: "list", feature: "suppliers", access: ["admin"], title: "Suppliers" },
  { path: "/suppliers/new", view: "new", feature: "suppliers", access: ["admin"], title: "Add supplier" },
  { path: "/suppliers/:id", view: "detail", feature: "suppliers", access: ["admin"], title: "Supplier detail" },
]
